---
port: 4443
ssl: true
ssl_key_file: /etc/ssl/server.key
ssl_cert_file: /etc/ssl/ssl-bundle.crt
environment: production
rackup: current/sync.ru
pid: shared/tmp/pids/faye.pid
log: shared/log/faye.log
socket: shared/tmp/sockets/faye.sock
chdir: /home/deploy/launchboard/
servers: 1
threaded: true
no-epoll: true
daemonize: true
